project:
  type: book

lang: "pt-BR"

book:
  title: "Laboratório de Genética Molecular - Nupgen - DBC/Nupélia"
  cover-image: cover.png
  favicon: favicon.png
  output-file: "book-nupgen"
  repo-url: https://github.com/nupgen/book_nupgen
  repo-actions: [issue]
  chapters:
    - index.qmd
    - lab.qmd
    - genetica-e-marcadores.qmd
    - part: "Protocolos"
      chapters: 
        - diluicoes.qmd
        - extracao.qmd
        - eletroforese.qmd
        - quantificacao.qmd
        - amplificacao.qmd
        - purificacao.qmd
        - sequenciamento.qmd
    - part: "Análises"
      chapters:
        - bancos-geneticos.qmd
        - softwares.qmd
        - pacotes-r.qmd
        - edicao-sequencias.qmd
        - alinhamento.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: 
      - cosmo
      - book_nupgen.scss
    link-external-icon: true
    link-external-newwindow: true
    #embed-resources: true
  pdf:
    documentclass: scrreprt

editor: visual

