---
title: "Coletas"
---

Todos os trabalhos do laboratório começam com a coleta de material biológico, por isso é fundamental que essa etapa seja feita de forma correta para não prejudicar os processos seguintes. Muito cuidado deve ser tomado desde o planejamento da coleta até sobre as informações registradas.

No Nupgen realizamos diversas coletas de peixes, caramujos, macrófitas e até de água. O PELD é um projeto que facilita bastante este processo de coleta.

## Campo

Toda viagem de campo é bem complicada, pois temos que fazer várias coisas com antecedência e não podemos esquecer nada.

### Licença de coleta

Toda coleta de material biológico deve ter uma licença de coleta, pois retirar animais silvestres da natureza é crime. Por isso é essencial conversar com os professores responsáveis antes e providenciar. Leve a autorização impressa dentro de um saco plástico transparente para não molhar. O PELD já possui uma licença geral de coleta.

### Local de coleta

Definir o local que será realizada a coleta é muito importante, pois quanto melhor o local, menos esforço amostral será necessário e, consequentemente, menos dinheiro será gasto. Converse com outras pessoas que já realizaram coletas no mesmo ambiente previamente.

É muito importante conhecer o ponto de coleta, bem como planejar a infraestrutura, alimentação e quantas pessoas serão necessárias.

Preparação para viagem

## Dados

Em qualquer coleta deve ser registrado o maior número de dados possível, afim de facilitar o trabalho futuro ou mesmo para prever possíveis questionamentos de revisores. Alguns dados muito importante são:

- Coordenadas;

- Espécie coletada;

- Número de espécimes;

- Local;

- Fotos e descrição do ambiente;


## Triagem

Após coletar os espécimes, é necessário realizar a triagem para garantir a qualidade do estudo. Com caramujos geralmente são triados os parasitos, com peixes podemos retirar o tecido, etc.






