# Diluições

As diluições são um procedimento comum em laboratório que consiste em misturar uma solução concentrada com uma solução diluente para produzir uma solução de concentração conhecida. Elas são utilizadas em diversas aplicações em laboratório, como preparação de amostras para análises químicas ou biológicas, padronização de soluções e muito mais.

Para realizar uma diluição, é necessário conhecer a concentração da solução inicial e a quantidade de solução diluente que será adicionada. A concentração da solução final pode ser calculada usando a fórmula de diluição:

$C1 * V1 = C2 * V2$

Onde $C1$ é a concentração da solução inicial, $V1$ é o volume da solução inicial, $C2$ é a concentração da solução final e $V2$ é o volume da solução final.

## Etanol

### Etanol 70%

**Para preparar 100ml**

Em um tubo tipo falcon, adicionar:

-   70 mL de etanol absoluto

-   30 mL de água destilada

### Etanol 80%

**Para preparar 100ml**

Em um tubo tipo falcon, adicionar:

-   80 mL de etanol absoluto

-   20 mL de água destilada

## GelRed

**Para preparar 500 μL**

Em um tubo de 1,5 mL envolto com fita e papel alumínio, adicionar:

-   1 μL de GelRed (estoque)

-   499 μL de água ultrapura (Milli-Q)

## Ladder 100pb (Invitrogen)

**Para preparar 100 μL**

Em um tubo de 1,5 mL, adicionar:

-   10 μL de Ladder (estoque 0,5 μg/μL)

-   90 μL de água ultrapura (Milli-Q)

## Ladder 100pb (Ludwig)

**Testando a diluição**

## Ladder 1kb

**Para preparar 100 μL**

Em um tubo de 1,5 mL, adicionar:

-   5 μL de Ladder (estoque 1 μg/μL)

-   95 μL de água ultrapura (Milli-Q)

## Lambda

### Lambda 5ng/μL (para 1000 μL)

-   9,27 μL de lambda (conferir concentração)

-   990,73 μL de água ultrapura (Milli-Q)

### Lambda 10ng/μL (para 1000 μL)

-   18,56 μL de lambda

-   981,44 μL de água ultrapura (Milli-Q)

### Lambda 20ng/μL (para 1000 μL)

-   37,11 μL de lambda

-   962,89 μL de água ultrapura (Milli-Q)

## Primer para uso (10 μM)

**Para preparar 60 μL**

Em um tubo, adicionar:

-   10 μL do primer estoque (60 μM - conferir concentração)

-   50 μL de água ultrapura (Milli-Q)

## Proteinase K 20 mg/mL

**Para preparar 1 mL**

-   20 mg de Proteinase K (estoque)

-   1 mL de água ultrapura (Milli-Q)

**Modo de preparo:** lavar bem uma espátula, fazer a desinfecção com álcool 70% e pesar a Proteinase K em um microtubo novo (1,5 mL). Adicionar a água ultrapura (Milli-Q) e ressuspender bem com a pipeta. Agitar a solução no vórtex para homogeneizar bem. Manter no freezer.

## Tampão TBE 5x (estoque)

**Para preparar 1000 mL**

-   54 g de Tris-Base

-   27,5 g de Ácido Bórico

-   20 mL de EDTA 0,5M pH 8,0

Completar para 1000 mL com água destilada

**Modo de preparo:** em um becker, adicionar um pouco da água destilada. Ir adicionando aos poucos os reagentes, utilizando o agitador magnético para homogeneizar a solução. Ao final, utilizando uma proveta, completar o volume de água que falta e armazenar em frascos de vidro (tampa laranja). Etiquetar e autoclavar.

## Tampão TBE 1x (corrida eletroforética)

**Para preparar 1000 mL**

$C1 * V1 = C2 * V2$

5(estoque) \* V1 = 1 \* 1000 mL

V1 = 1000/5

V1 = 200 mL de TBE 5x

Completar para 1000 mL de água destilada (= 800 mL)

## Tampão Coleta Macrófitas

**Para preparar 1000 mL**

-   Tris HCl - 10 mL

-   EDTA (0,5mM) - 2 mL

-   Água destilada - 988ml

pH = 8,0

**Modo de preparo:** Colocar 10ml do Tris HCl e 2ml do EDTA (0,5mM) em um frasco de vidro (tampa laranja ou azul), completar o volume com água destilada. Agitar o frasco para misturar bem e medir o pH com as fitinhas, para conferir se está correto; caso não esteja, basta ajustar com as soluções para pH. Etiquetar e autoclavar.

## PEG 20% NaCl 2,5M

**Para preparar 75 mL**

-   15 g de Polietilenoglicol

-   10,95 g de NaCl

Completar o volume para 75 mL com água ultrapura (Milli-Q)

**Modo de preparo:** colocar em um becker um pouco da água ultrapura e misturar o Polietilenoglicol e o NaCl com um bastão de vidro até a solução ficar homogênea. Depois de homogeneizada, completar o volume de água para 75 mL e com o auxílio de uma seringa passar a solução por um filtro (0,2 µM -- azul). Acondicionar em tubos Falcon para autoclavar. Após autoclavado, fazer alíquotas em microtubos de 1,5 mL. Manter no freezer da geladeira.

## Diluição de primer liofilizado

**Quantidade em nmol x 1000 / 60 = Quantidade de água ultrapura (Milli-Q)**

Acrescentar a quantidade obtida de água diretamente no tubo do primer liofilizado.

Obs: 60 µM é a concentração utilizada para diluição dos primers no laboratório.
