# Genética Molecular e Marcadores

## O que é a genética molecular?

A Genética Molecular utiliza o DNA como objeto de estudo. O DNA (ácido desoxirribonucleico) é uma biomolécula capaz de armazenar a informação biológica e perpetuá-la pelo processo de auto replicação semiconservativa. Sua estrutura é uma dupla-fita helicoidal de nucleotídeos, que por sua vez é composta por um grupo fosfato, uma pentose e uma base nitrogenada. As duas fitas de DNA são unidas por meio de ligações de hidrogênio entre as bases nitrogenadas. Existem quatro bases nitrogenadas: Adenina (A), Timina (T), Citosina (C) e Guanina (G), sendo a Adenina complementar à Timina, e a Citosina complementar à Guanina. Portanto, uma fita de DNA consiste em uma sequência de nucleotídeos, cuja ordem das bases nitrogenadas (A, T, C, G) determinaram as características biológicas. Embora as células possuam um aparato enzimático complexo que garante uma alta fidelidade nas sequências nucleotídicas durante a replicação do DNA, alguns "erros de replicação" podem ser perpetuados. Esses "erros", além de fatores ambientais (como a radiação, por exemplo), podem levar a mutações. As mutações são a fonte do polimorfismo genético, que consiste no principal objetivo que permeia as pesquisas na área da Biologia Molecular. Conhecer com profundidade os mecanismos moleculares envolvidos na estrutura e replicação do DNA é importante para garantir o entendimento dos protocolos e o domínio das análises feitas no laboratório, por isso, recomenda-se a leitura de livros-base na área da Biologia Molecular e Genética. Segue abaixo uma lista das principais referências na área:

@brucealberts2017

@anthonyj.f.griffiths2016

@petersnustad2017

## Marcadores Moleculares
