# Início {.unnumbered}

Este é o livro online do **Nupgen**, o **Laboratório de Genética Molecular do Nupélia (DBC/Nupélia)**. Aqui você poderá encontrar textos explicativos sobre nossa linha de pesquisa, as metodologias utilizadas em nosso laboratório, bem como os protocolos atualizados. Este é um material introdutório destinado principalmente aos alunos do laboratório e pode servir como guia para as tarefas mais técnicas. Esperamos que ele funcione como um Procedimento Operacional Padrão (POP) em nosso laboratório, mantendo as equipes alinhadas, elevando a produtividade e evitando o desperdício de recursos dentro do laboratório. Este livro não precisa ser lido de forma sequencial e cada capítulo é independente de outros, no entanto, organizamos os capítulos seguindo a lógica de trabalho no laboratório para tornar a leitura mais fluida.

O objetivo deste livro não é substituir a colaboração entre alunos do laboratório, mas sim garantir que pequenos detalhes não sejam perdidos com o passar do tempo. Na verdade, esperamos que os tópicos deste livro sejam exaustivamente discutidos entre os alunos, a fim de melhorar este conteúdo e gerar novas perguntas que ajudem no desenvolvimento da pesquisa.

Uma versão em PDF deste livro pode ser acessada pelo seguinte link: [Livro PDF](https://github.com/nupgen/book_nupgen/blob/master/_book/book-nupgen.pdf)

Este livro foi escrito em [Quarto](https://quarto.org/).

**Organização: Bruno Mioto**

**Autores: Adrian Silva, Bárbara Scorsim, Bruno Mioto, Eloisa de Páris e Mayara Passere**
